# Site Settings
title               : pRoJEct-VeXEd
owner               : "DeerRIDER"
## url                : "https://akiritsu.github.io"
## baseurl            : "/pRoJEct-VeXEd"
permalink           : /:title/
description         : "A hacker-style note-keeping website template."
markdown            : kramdown

# Where things are
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# Collections
collections:
  posts:
    output          : true
    permalink       : /:collection/:title/
  notes:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
  portfolio:
    output          : true
    permalink       : /:collection/:title/
    order: # specify post order manually
      - portfolio3.md
      - portfolio2.md
      - portfolio1.md
  album:
    output          : true
    permalink       : /:collection/:title/
    sort_by         : date
      
# Social Media Accounts
email               : "just-test" 
linkedin            : 
github              : "just-test" 
gitlab              : 
website             : 
twitter             : "just-test"
facebook            : "just-test"
instagram           : 
youtube             : "just-test"
steam               : "just-test"
weibo               : "just-test"

# Global Variables
statement           : "Designed by DeerRIDER, All Rights Reserved"
toc_level           : 3
bgtext              : "ABCFGHKLMNPQRSVWXYZabcdefghijklmnopqrstuvwxyz@#$%&*+-;/[]<>~" # texts randomly displayed in background

# Default page configuration
defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
  -    
    scope:
      path: ""
      type: notes # file under notes
    values:
      layout: "post"
      tags: n0t3s
      author: aaa
  -    
    scope:
      path: ""
      type: portfolio
    values:
      layout: "post"
      tags: pfl

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Cross-Origin Resource Sharing header
webrick:
  headers:
    Access-Control-Allow-Origin: "*"