## Settings
title: "h3ll0 w0rld!"
owner: "0cool-f"
url: "https://0cool-f.github.io"
baseurl: "/jekyll"
permalink: /:title/
description: "questo ostico jekill"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "ravnos.1@tiscali.it"
github: "0cool-f/jekyll"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets"
statement: "welcome to this Jekyll thing"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"

# Enter your Google Analytics web tracking code (e.g. UA-153211609-1) to activate tracking
# google_analytics: UA-XXXXXXXXX-X

# css compress
sass:
  style: :compressed

# html compress settings
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: all
#  blanklines: true
#  profile: false
#  startings: [] # all
# ["<!-- ", " -->"]

plugins:
  - jekyll-minifier
