title: pRoJEct-NeGYa
url: "akiritsu.github.io/"
# baseurl: "pRoJEct-NeGYa"
description: ""
email: "deerrider@outlook.com"
github: "akiritsu"
access_token: true
statement: "本网站归个人所有，所有信息都他吗我的"

markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
# plugins:
webrick:
  headers:
    Access-Control-Allow-Origin: "*"