title: Progject NeGYa
url: "akiritsu.github.io"
baseurl: "/pRoJEkt-NeGYa"
description: ""
email: deerrider@outlook.com

markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# plugins: