title: pRoJEct-NeGYa
owner: "DeerRIDER"
url: "akiritsu.github.io"
baseurl: ""
# baseurl: "/pRoJEct-NeGYa"
permalink: /:title/

description: ""
email: "deerrider@outlook.com"
github: "akiritsu"
statement: "Designed by DeerRIDER, All Rights Reserved"
# list of articles title
loa_title: "List of Articles"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3

markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"